merging updates to configure script

diff --git a/src/xmitmsgx/configure b/src/xmitmsgx/configure
--- a/src/xmitmsgx/configure
+++ b/src/xmitmsgx/configure
@@ -2,6 +2,9 @@
 #
 #         Name: configure (shell script)
 #               part of the standard recipe
+#               set-up the source directory for [re]making
+#       Author: Rick Troth, Houston, Texas, USA
+#         Date: 1997-Feb-02
 #       Author: Rick Troth, rogue programmer
 #         Date: 2023-03-16 (Thu) and following
 #               2023-06-28 (Wed) added sub-project support
@@ -14,12 +17,19 @@
 #               configure.h
 #
 
+#
+# run from the resident directory
 cd `dirname "$0"`
-#D=`pwd`
+Z=`basename $0`
 A="$*"
 
+#
+# set a default installation prefix
+#PREFIX=/usr/local
 PREFIX=/usr
 
+#
+# parse arguments and options
 while [ ! -z "$*" ] ; do
     case "$1" in
         --prefix)
@@ -46,8 +56,17 @@ while [ ! -z "$*" ] ; do
     shift
 done
 
-LOCDIR=$PREFIX/share/locale                               # for xmitmsgx
 #
+# establish build defaults
+CFLAGS=""
+#CFLAGS="-DOECS"
+LDFLAGS=""
+LIBS=""
+
+LOCDIR=$PREFIX/share/locale                               # for xmitmsgx
+
+#
+# identify this environment/system
 US=`uname -s | sed 's#/##g'`
 UM=`uname -m | sed 's#^i.86$#i386#' | sed 's#^armv.l$#arm#'`
 case "$US" in
@@ -73,26 +92,50 @@ case "$US" in
         UM=`uname -p`
         LIBS="-lsocket -lnsl"
         ;;
-    OS390)
+    OS390)              # OS/390, z/OS
         UM="s390x" # guessing! since both "s390x" and "s390" are viable
         CC="xlc"
+        CFLAGS="-DOECS -D_OE_SOCKETS"
         LDFLAGS="-O -qxplink"
         SHFLAGS="$LDFLAGS -qdll"
         if [ -d /usr/lib/nls/msg ] ; then LOCDIR=/usr/lib/nls/msg ; fi
         ;;
+    zVM|VMESA)          # VM/ESA, z/VM
+        UM="s390" # guessing! but CMS is historically slow w/r/t 64-bit
+        CC="xlc"
+        CFLAGS="-DOECS -D_OE_SOCKETS"
+        LIBS="-l//posxsock -l//vmmtlib"
+        ;;
 esac
 
-#examples:
+#LOCALE examples:
 #/usr/share/locale/
 #/usr/lib/nls/msg/
 #/usr/share/nls/
 #LOCALE=en_US.UTF-8
 #LOCALE=en_US
 
+#
 # use the system string we just derived or override from Chicory
 if [ ! -z "$CHICORY_SYSTEM" ] ; then SYSTEM=$CHICORY_SYSTEM
                                 else SYSTEM="$US-$UM" ; fi
 
+#
+# announce
+echo "$Z: setting up 'sendfile' for $SYSTEM ..."
+
+#
+# silently move old makefile aside:
+mv makefile makefile.old 2>/dev/null
+
+#
+# start a fresh "makefile" and stamp it:
+echo "# this file generated by '$0'" > makefile
+RC=$? ; if [ $RC -ne 0 ] ; then exit $RC ; fi
+date +'# %Y-%b-%d %T %Z %a' >> makefile
+RC=$? ; if [ $RC -ne 0 ] ; then exit $RC ; fi
+
+#
 # create proper makefile from reference input
 cat makefile.in \
   | sed "s#%CFLAGS%#$CFLAGS#g" \
@@ -100,10 +143,13 @@ cat makefile.in \
   | sed "s#%SYSTEM%#$SYSTEM#g" \
   | sed "s#%LDFLAGS%#$LDFLAGS#g" \
   | sed "s#%SHFLAGS%#$SHFLAGS#g" \
+  | sed "s#%LIBS%#$LIBS#g" \
   | sed "s#%LOCDIR%#$LOCDIR#g" \
   | sed 's#^        #\t#' \
-  > makefile
+  >> makefile
+RC=$? ; if [ $RC -ne 0 ] ; then exit $RC ; fi
 
+#
 # create configuration header file and sourcable shell script
 rm -f configure.tmp
 echo "CFLAGS=#$CFLAGS#"   >> configure.tmp
@@ -115,15 +161,18 @@ echo "LOCDIR=#$LOCDIR#"   >> configure.tmp                    # xmitmsgx
 sed 's/#/"/g' < configure.tmp | awk '{print "#define" , $0}' | sed 's/=/ /' > configure.h
 sed 's/#/"/g' < configure.tmp > configure.sh # chmod a+x configure.sh
 rm configure.tmp
-#define VERSION not needed
-#define LOCALE not needed
+#define VERSION not needed here
+#define LOCALE not needed here
 
+#
 # for each sub-project run the 'configure' script found there
 for F in */configure ; do
     if [ -x $F -a -f $F ] ; then
         echo "+ $F $A"
         $F $A ; fi
 done
+
+echo "$Z: done."
 
 exit
 
